pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/tu_usuario/tu_repositorio.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    docker.build('mi-imagen', '.')
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    docker.image('mi-imagen').inside {
                        sh 'dotnet test'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Aquí puedes agregar el código para desplegar tu aplicación.
                    // Ejemplo: `sh 'docker push mi-imagen'`
                    sh 'docker-compose up -d'
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
